In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_parquet('../data/application_clean.parquet')
df

,sk_id_curr,target,name_contract_type,code_gender,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,...,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year,credit_over_goods,fee_band,age_years,social_def_rate_30
0,100002,1,0,1,0,1,0,202500.0,406597.5,24700.5,...,0.0,0.0,0.0,0.0,0.0,1.0,1.158397,fees_added,25.903338,1.0
1,100003,0,0,0,0,0,0,270000.0,1293502.5,35698.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.145199,fees_added,45.901011,0.0
2,100004,0,1,1,1,1,0,67500.0,135000.0,6750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,no_fees,52.146177,NaN
3,100006,0,0,0,0,1,0,135000.0,312682.5,29686.5,...,NaN,NaN,NaN,NaN,NaN,NaN,1.052803,fees_added,52.033923,0.0
4,100007,0,0,1,0,1,0,121500.0,513000.0,21865.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,no_fees,54.571962,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307502,456251,0,0,1,0,0,0,157500.0,254700.0,27558.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.132000,fees_added,25.536459,NaN
307503,456252,0,0,0,0,1,0,72000.0,269550.0,12001.5,...,NaN,NaN,NaN,NaN,NaN,NaN,1.198000,fees_added,56.880018,NaN
307504,456253,0,0,0,0,1,0,153000.0,677664.0,29979.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.158400,fees_added,40.975516,0.0
307505,456254,1,0,0,0,1,0,171000.0,370107.0,20205.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.158394,fees_added,32.748106,NaN


In [2]:
ids = df['sk_id_curr']
X = df.drop(columns = ['target', 'sk_id_curr'])
y = df['target']

print(f'ID data:\n{ids.head()}\n')
print(f'Train data:\n{X.head()}\n')
print(f'Target data:\n{y.head()}')

#Temporary will be splitten again to create a seperate data to build an EV threshold model on unseen data.
#Ids are kept in seperate data(while being connected to our main data), this is done to have the option later on to connected the datasets
#using clients IDS
X_temporary, X_test, y_temporary, y_test, ids_temporary, ids_test = train_test_split(X, y, ids, test_size = 0.2, random_state = 42)
X_train, X_evModel, y_train, y_evModel, ids_train, ids_evModel = train_test_split(X_temporary, y_temporary, ids_temporary, test_size = 0.25, random_state = 42)

ID data:
0    100002
1    100003
2    100004
3    100006
4    100007
Name: sk_id_curr, dtype: int64

Train data:
   name_contract_type  code_gender  flag_own_car  flag_own_realty  \
0                   0            1             0                1   
1                   0            0             0                0   
2                   1            1             1                1   
3                   0            0             0                1   
4                   0            1             0                1   

   cnt_children  amt_income_total  amt_credit  amt_annuity  amt_goods_price  \
0             0          202500.0    406597.5      24700.5         351000.0   
1             0          270000.0   1293502.5      35698.5        1129500.0   
2             0           67500.0    135000.0       6750.0         135000.0   
3             0          135000.0    312682.5      29686.5         297000.0   
4             0          121500.0    513000.0      21865.5         513000.0  

In [3]:
print(f'60% Train:{X_train.shape, y_train.shape, ids_train.shape} \n20% Test:{X_test.shape, y_test.shape, ids_test.shape} \n20% evModel:{X_evModel.shape, y_evModel.shape}')

60% Train:((184503, 84), (184503,), (184503,)) 
20% Test:((61502, 84), (61502,), (61502,)) 
20% evModel:((61502, 84), (61502,))


In [4]:
#Splitting the learning data into two datas, one represeting numerical data and the other categorical data.
#It is required for this dataset because categorical and numerical data require different treatment.

categorical_cols = X.select_dtypes('object').columns.tolist()
numerical_cols = X.select_dtypes('number').columns.tolist()

print(len(categorical_cols), "categorical")
print(len(numerical_cols), "numeric")
print(f'target in X: {'target' in X.columns} | sk_id_curr in X:{'sk_id_curr' in X.columns}')
print(f'Categorical + Numerical columns sum:{len(categorical_cols) + len(numerical_cols)}, Learning data columns sum:{X.shape[1]}')

13 categorical
71 numeric
target in X: False | sk_id_curr in X:False
Categorical + Numerical columns sum:84, Learning data columns sum:84


In [5]:
#Numerical pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

imputer = SimpleImputer(missing_values=np.nan, strategy='median')
X_train_num_imputed = imputer.fit_transform(X_train[numerical_cols])

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_num_imputed)

print(X_train_scaled.shape, X_train_scaled.mean(axis=0)[:3].round(3))

(184503, 71) [ 0. -0. -0.]


In [6]:
#Categorical pipeline
from sklearn.preprocessing import OneHotEncoder

cat_imputer = SimpleImputer(strategy="most_frequent")
X_train_cat_imputed = cat_imputer.fit_transform(X_train[categorical_cols])

cat_encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
X_train_encoded = cat_encoder.fit_transform(X_train_cat_imputed)

print(X_train_encoded.shape)
print(X_train_encoded.sum(axis=1)[:5])
print(cat_encoder.get_feature_names_out()[:10])
print(pd.isna(X_train_cat_imputed).sum().sum())

(184503, 140)
[13. 13. 13. 13. 13.]
['x0_Children' 'x0_Family' 'x0_Group of people' 'x0_Other_A' 'x0_Other_B'
 'x0_Spouse, partner' 'x0_Unaccompanied' 'x0_Unknown' 'x1_Businessman'
 'x1_Commercial associate']
0


In [7]:
nan_cols = pd.DataFrame(X_train_cat_imputed, columns=categorical_cols).isna().sum()
print(nan_cols[nan_cols > 0])

Series([], dtype: int64)


In [8]:
col = 'name_type_suite'
print(X_train[col].isna().sum())
print(X_train[col].value_counts(dropna=False).head(10))\
# df['name_type_suite'] = df['name_type_suite'].fillna('Unknown') added to the cleaning notebook.

0
name_type_suite
Unaccompanied      149196
Family              24048
Spouse, partner      6789
Children             1952
Other_B              1055
Unknown               797
Other_A               516
Group of people       150
Name: count, dtype: int64


In [9]:
#final merge
X_train_ready = np.hstack([X_train_scaled, X_train_encoded])
print(X_train_ready.shape)
feature_names = list(numerical_cols) + list(cat_encoder.get_feature_names_out())
print(len(feature_names), X_train_ready.shape[1])

(184503, 211)
211 211


In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

logreg = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42,
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(logreg, X_train_ready, y_train,cv=cv, scoring='average_precision', n_jobs=-1)

pred_reg = cross_val_predict(logreg, X_train_ready, y_train, cv=cv)

print(scores.round(4))
print('mean', scores.mean().round(4), '| spread', (scores.max() - scores.min()).round(4))
print('baseline', y_train.mean().round(4))
print(confusion_matrix(y_train, pred_reg))

[0.2231 0.2126 0.2202 0.2163 0.212 ]
mean 0.2168 | spread 0.0112
baseline 0.0805
[[116942  52700]
 [  4909   9952]]


In [11]:
from xgboost import XGBClassifier

# categoricals still need encoding — reuse the already-fitted encoder
X_train_cat_for_xgb = cat_encoder.transform(
    cat_imputer.transform(X_train[categorical_cols])
)

# numerics go in raw: NaNs intact, no scaling
X_train_xgb = np.hstack([
    X_train[numerical_cols].to_numpy(),
    X_train_cat_for_xgb,
])

print(X_train_xgb.shape)
print('NaNs kept:', np.isnan(X_train_xgb).sum())

(184503, 211)
NaNs kept: 2146947


In [24]:
xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    eval_metric='aucpr',
    n_jobs=-1,
    random_state=42,
)

scores_xgb = cross_val_score(xgb, X_train_xgb, y_train,cv=cv, scoring='average_precision',)

proba_xgb = cross_val_predict(xgb, X_train_xgb, y_train, cv=cv, method='predict_proba')[:, 1]

print(scores_xgb.round(4))
print('mean', scores_xgb.mean().round(4))

#Logistic regression rejected 34% of applicants 66,652 out of 184,503 and caught 9,952.
#I put the same threshold (100%-66%) so they will have a fair comparison and we can evaluate how changing the model affected the outcome
threshold = np.percentile(proba_xgb, 66)
print(confusion_matrix(y_train, (proba_xgb >= threshold).astype(int)))

[0.2431 0.2331 0.2388 0.2377 0.2301]
mean 0.2366
[[117107  52535]
 [  4665  10196]]


In [22]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'max_depth':[3, 4, 5, 6],
    'learning_rate':[0.02, 0.03, 0.05, 0.08],
    'n_estimators':[300, 500, 700],
    'subsample':[0.7, 0.85, 1.0],
    'colsample_bytree':[0.5, 0.7, 0.9],
    'min_child_weight':[1, 5, 10, 20],
    'reg_lambda':[1, 5, 10, 20],
}

xgb_full = XGBClassifier(eval_metric='aucpr', n_jobs=-1, random_state=42)

search = RandomizedSearchCV(xgb_full, param_distributions=param_dist, n_iter=20,scoring='average_precision', cv=cv, random_state=42, verbose=1,)

search.fit(X_train_xgb, y_train)

proba_tuned = cross_val_predict(search.best_estimator_, X_train_xgb, y_train, cv=cv, method='predict_proba')[:, 1]

print(round(search.best_score_, 4), search.best_params_)
print(confusion_matrix(y_train, (proba_tuned >= 0.5).astype(int)))

Fitting 5 folds for each of 20 candidates, totalling 100 fits


Exception ignored on calling ctypes callback function <bound method DataIter._next_wrapper of <xgboost.core.SingleBatchInternalIter object at 0x00000160E96BC050>>:
Traceback (most recent call last):
  File "C:\Users\Maria Pilipenko\anaconda3\Lib\site-packages\xgboost\core.py", line 425, in _next_wrapper
    def _next_wrapper(self, this: None) -> int:  # pylint: disable=unused-argument
KeyboardInterrupt: 


KeyboardInterrupt: 